import Head from "next/head";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { useEffect, useState } from "react";
import Navigation from "../components/Navigation";
import Link from "next/link";

export default function Home() {
  const [listOfPosts, setListOfPosts] = useState([]);
  useEffect(() => {
    axios.get("http://localhost:3001/posts").then((response) => {
      setListOfPosts(response.data);
    });
  }, []);
  return (
    <div>
      <Head>
        <title>Fullstack app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <div className="App">
        {listOfPosts.map((value, key) => {
          return (
            <Link key={value.id} href="post/[id]" as={`/post/${value.id}`}>
              <a>
                <div className="post">
                  <div className="title">{value.title}</div>
                  <div className="body">{value.postText}</div>
                  <div className="footer">{value.username}</div>
                </div>
              </a>
            </Link>
          );
        })}
      </div>
    </div>
  );
}
