import Head from "next/head";
import axios from "axios";
import { useEffect, useState } from "react";
import Link from "next/link";
import Layout from "../components/Layout";

export default function Home() {
  const [listOfPosts, setListOfPosts] = useState([]);

  useEffect(() => {
    axios.get("http://localhost:3001/posts").then((response) => {
      setListOfPosts(response.data);
    });
  }, []);

  return (
    <>
      <Head>
        <title>Fullstack app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {listOfPosts.map((value, key) => {
          return (
            <Link key={value.id} href="post/[id]" as={`/post/${value.id}`}>
              <a>
                <div className="post">
                  <div className="title">{value.title}</div>
                  <div className="body">{value.postText}</div>
                  <div className="footer">{value.username}</div>
                </div>
              </a>
            </Link>
          );
        })}
      </Layout>
    </>
  );
}
