import Head from "next/head";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { useEffect, useState } from "react";
import Navigation from "../components/Navigation";

export default function Home() {
  const [listOfPosts, setListOfPosts] = useState([]);
  useEffect(() => {
    axios.get("http://localhost:3001/posts").then((response) => {
      setListOfPosts(response.data);
    });
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Fullstack app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="App">
        <Navigation />
        {listOfPosts.map((value, key) => {
          return (
            <div className="post" key={value.id}>
              <div className="title">{value.title}</div>
              <div className="body">{value.postText}</div>
              <div className="footer">{value.username}</div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
